import Head from 'next/head'
import Image from 'next/image'
import { getSortedPostsData } from '../lib/posts'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home({allPostsData}) {
  return (
    <>
      <Head>
        <title>fengd's Zone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        {/* Add this <section> tag below the existing <section> tag */}
        <h1>Recent posts</h1>
        <article className={styles.article}>
          <ul className={styles.posts}>
            {allPostsData.map(({ id, date, title, spoiler }) => (
              <li key={id}>
                <h3>
                  <Link href={`/posts/${encodeURIComponent(id)}`}>{title}</Link>
                </h3>
                <small>
                  {new Date(date).toLocaleDateString()}
                </small>
                <p>
                  {spoiler}
                </p>
              </li>
            ))}
          </ul>
        </article>
      </main>
    </>
  )
}


export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  console.log(allPostsData)
  return {
    props: {
      allPostsData,
    },
  };
}
